In [18]:
!pip install fpdf

Collecting fpdf
  Downloading fpdf-1.7.2.tar.gz (39 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: fpdf
  Building wheel for fpdf (setup.py) ... done
  Created wheel for fpdf: filename=fpdf-1.7.2-py2.py3-none-any.whl size=40702 sha256=7a4ca41e7ce1ba37572ad1c56456501540029c822703198a788e954bb6f22d91
  Stored in directory: /home/vishnu/.cache/pip/wheels/6e/62/11/dc73d78e40a218ad52e7451f30166e94491be013a7850b5d75
Successfully built fpdf
Installing collected packages: fpdf
Successfully installed fpdf-1.7.2

In [16]:
import tabula
tabels = tabula.read_pdf('18_unlocked.pdf')

'pages' argument isn't specified.Will extract only from page 1 by default.

[          USN              Name 15MAT11 15CIV13 15ELE15  SGPA  CGPA
 0  1AM16CS085           MANOJ S       F       -       -  3.39  5.77
 1  1AM16CS088           MO AKIL       F       F       -  2.86  5.96
 2  1AM16CS152      SANJU SAHANI       E       -       -  2.86  4.91
 3  1AM16CS158      SHILPIKA M M       F       -       -  3.06  5.93
 4  1AM16CS208  AISHWARYA MARY K       F       -       F  1.11  5.76]

In [3]:
tabula.convert_into("18.pdf", '18.csv')

'pages' argument isn't specified.Will extract only from page 1 by default.

In [4]:
import pandas as pd

df = pd.read_csv('18.csv')
df

          USN              Name 15MAT11 15CIV13 15ELE15  SGPA  CGPA
0  1AM16CS085           MANOJ S       F       -       -  3.39  5.77
1  1AM16CS088           MO AKIL       F       F       -  2.86  5.96
2  1AM16CS152      SANJU SAHANI       E       -       -  2.86  4.91
3  1AM16CS158      SHILPIKA M M       F       -       -  3.06  5.93
4  1AM16CS208  AISHWARYA MARY K       F       -       F  1.11  5.76

In [7]:
new_df = df[['USN', 'Name', 'CGPA']]
new_df

          USN              Name  CGPA
0  1AM16CS085           MANOJ S  5.77
1  1AM16CS088           MO AKIL  5.96
2  1AM16CS152      SANJU SAHANI  4.91
3  1AM16CS158      SHILPIKA M M  5.93
4  1AM16CS208  AISHWARYA MARY K  5.76

In [10]:
unc = pd.DataFrame(new_df)
unc

          USN              Name  CGPA
0  1AM16CS085           MANOJ S  5.77
1  1AM16CS088           MO AKIL  5.96
2  1AM16CS152      SANJU SAHANI  4.91
3  1AM16CS158      SHILPIKA M M  5.93
4  1AM16CS208  AISHWARYA MARY K  5.76

In [11]:
unc.to_csv('Output1')

In [12]:
len(unc)

5

In [23]:
import camelot
from fpdf import FPDF

# Define the input and output PDF paths
input_pdf_path = "18_unlocked.pdf"
output_pdf_path = "extracted_tables.pdf"

# Extract tables from the specified pages using Camelot
# Adjust the pages parameter as needed (e.g., '44-48' for pages 44 to 48)
tables = camelot.read_pdf(input_pdf_path, pages='44-48')

# Create a PDF document to store the extracted tables
pdf = FPDF()
pdf.set_auto_page_break(auto=True, margin=15)
pdf.add_page()
pdf.set_font("Arial", size=12)

# Add each table to the PDF
for table in tables:
    pdf.add_page()
    table_data = table.df.values.tolist()
    for row in table_data:
        row_text = ' | '.join(map(str, row))
        pdf.cell(200, 10, txt=row_text, ln=True)

# Save the output PDF
pdf.output(output_pdf_path)

print(f"Extracted tables have been saved to {output_pdf_path}")

ModuleNotFoundError: No module named 'ghostscript'

In [25]:
import camelot

input_pdf_path = "18_unlocked.pdf"

# Test extracting tables from the specified pages using Camelot
try:
    tables = camelot.read_pdf(input_pdf_path, pages='44-48')
    print(f"Successfully extracted {len(tables)} tables")
except Exception as e:
    print(f"An error occurred: {e}")

An error occurred: No module named 'ghostscript'